<?php

/**
 * @file
 * Hook implementations for REST UI module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function restui_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'restui.edit':
      return '<p>' . t('Here you can restrict which HTTP methods should this resource support. And within each method, the available serialization formats and authentication providers.') . '</p>';
  }
}

/**
 * Implements hook_theme().
 */
function restui_theme($existing, $type, $theme, $path) {
  return [
    // List resources.
    'restui_resource_info' => [
      'variables' => [
        'granularity' => [],
        'configuration' => [],
      ],
      'template' => 'restui-resource-info',
    ],
    'inicio' => [
            'render element' => 'inicio',
            'path' => $path . '/templates',
            'template' => 'inicio',
            'variables' => [
                'var1' => 'value',
            ],
        ],
  ];
}
